# Generated by Django 4.2 on 2024-11-19 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок', max_length=50, verbose_name='Заголовок')),
                ('body', models.TextField(help_text='Введите текст', verbose_name='Текст')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'verbose_name': 'Запись в дневнике',
                'verbose_name_plural': 'Записи в дневнике',
            },
        ),
    ]
