# Generated by Django 4.2 on 2024-11-22 16:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="diary",
            unique_together={("user", "create_date")},
        ),
    ]
