# Generated by Django 4.2 on 2024-11-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diary_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ('create_date',), 'verbose_name': 'Запись в дневнике', 'verbose_name_plural': 'Записи в дневнике'},
        ),
    ]
